//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adotar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adotarEntities : DbContext
    {
        public adotarEntities()
            : base("name=adotarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animal> animal { get; set; }
        public virtual DbSet<bairro> bairro { get; set; }
        public virtual DbSet<cidade> cidade { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<interesse> interesse { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
