//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adotar
{
    using System;
    using System.Collections.Generic;
    
    public partial class interesse
    {
        public long id { get; set; }
        public string texto { get; set; }
        public long Animal_id { get; set; }
        public long Usuario_id { get; set; }
    
        public virtual animal animal { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
